#!/usr/bin/env node
var rc= require("rc")("ridesnag-bookshelf")

var moar= Array.prototype.splice(process.argv,1).join(" ")

console.log("psql -U"+rc.connection.user+" -h"+rc.connection.host+" -p"+rc.connection.port+" -W|"+moar+"|")
